Feat/docker compose
atls/team-management pull request #10
Opened 2024-05-07 17:00 UTC by effektivnayarabota1

closes https://github.com/atls/team-management/issues/3

дал название скриптов по названию `workspace`
в тех примерах, что ты приложил была нода 18.13. у меня на такую версию ругался `next`, я увеличил

2024-05-07 17:33 UTC, Nelfimov requested changes

2024-05-07 17:33 UTC, Nelfimov commented on docker-compose.yml
> +    image: node:18.18
бери 18 LTS

2024-05-07 17:33 UTC, Nelfimov commented on docker-compose.yml
> +version: '3.8'
это уже лишнее - не требуется

2024-05-07 17:33 UTC, Nelfimov commented on docker-compose.yml
> +  identity:
это и ниже - у тебя пока только один сервис будет - `app` вот его и добавляй

2024-05-08 04:55 UTC, effektivnayarabota1 commented on docker-compose.yml
> +  identity:
давал название скриптов по имени в [`package.json`](https://github.com/atls/team-management/blob/a3d9e52eda2eb27534108dc6e9b413a8e0b6b305/app/entrypoints/renderer/package.json)

2024-05-08 05:23 UTC, Nelfimov requested changes

2024-05-08 05:23 UTC, Nelfimov commented on docker-compose.yml
> +  app-build:
этот сервис и ниже - нам `docker compose` обычно нужен для локальной разработки и взаимосвязи с другими сервисами. Поэтому кроме `dev` ничего не нужно.

2024-05-08 05:23 UTC, Nelfimov commented on docker-compose.yml
> +    entrypoint: yarn workspace @identity/renderer-entrypoint dev
Кажется ты это не запускал - запусти `docker compose up` из корня проекта и посмотри что будет.

2024-05-08 05:25 UTC, effektivnayarabota1 commented on docker-compose.yml
> +    entrypoint: yarn workspace @identity/renderer-entrypoint dev
да, через `up` у меня не запускался, запускал скрипт `yarn` через `run` и просто `app` через `start`

2024-05-08 06:31 UTC, Nelfimov requested changes

2024-05-08 06:31 UTC, Nelfimov commented on docker-compose.yml
> +    entrypoint: yarn workspace @identity/renderer-entrypoint dev
так надо же запускать энтрипоинт - иначе ты ссылаешься на несуществующий сервис.

Тебе надо прийти к тому, что ты запускаешь `docker compose up` и по 3000 порту в браузере получишь наш энтрипоинт.

2024-05-08 06:32 UTC, Nelfimov commented
@effektivnayarabota1 виноват, не увидел что энтрипоинт называется `identity`

Переименуй его в `app` и скорректируй `docker-compose`

2024-05-08 06:59 UTC, Nelfimov approved these changes

2024-05-08 06:59 UTC, merged