feat: input component
atls/team-management pull request #12
Opened 2024-05-08 18:10 UTC by effektivnayarabota1

https://github.com/atls/team-management/issues/11

2024-05-08 18:19 UTC, effektivnayarabota1 commented
# хочу отрендерить компонент `Input` на странице, убедиться что все работает.

в инпут не попадают свойства `theme`
``` typescript
 ⨯ ../.yarn/__virtual__/@ui-input-virtual-6615bb79b7/1/ui/input/src/input.styles.ts (31:26) @ input
 ⨯ TypeError: Cannot read properties of undefined (reading 'input')
    at primaryColorsStyles (../../../../.yarn/__virtual__/@ui-input-virtual-6615bb79b7/1/ui/input/src/input.styles.ts:38:37)
  29 | export const primaryColorsStyles = ({theme}) => ({
  30 | 	...createAppearanceStyles({
> 31 | 		fontColor: theme.colors.input.font,
     | 		                      ^
  32 | 		backgroundColor: theme.colors.input.background,
  33 | 		borderColor: theme.colors.input.border,
  34 | 	})(),
```

для теста добавил в объект `theme` эти свойства, в `theme.provider` выходит такой лог,:
тоесть это свойство в объекте есть.
```typescript
{ font: 'rgb(128, 127, 127)' }
```
мне кажется, что ошибка где-то тут, не понимаю как передается объект `theme` в компонент `Input`
```typescript
const Page = () => {
	return (
		<ThemeProvider>
			<Input
				placeholder='input-placeholder'
			/>
		</ThemeProvider>
	)

}
```

2024-05-09 06:37 UTC, Nelfimov requested changes
1. Пользуйся `yarn format` для читаемости кода
2. У тебя потерялся контекст - `@emotion/react` как зависимость была только у `theme`, а `@ui/input` ее не видел. Обрати внимание на мой коммит

2024-05-09 06:37 UTC, Nelfimov commented
Ну и в добавок - нейминг веток. Имена собственные не допускаются.

2024-05-09 07:04 UTC, effektivnayarabota1 commented
> Ну и в добавок - нейминг веток. Имена собственные не допускаются.

![image](https://github.com/atls/team-management/assets/70315473/bdad8903-d2e8-4c7e-bc8f-aaa00d184678)

2024-05-09 07:06 UTC, Nelfimov commented
> > Ну и в добавок - нейминг веток. Имена собственные не допускаются.
> 
> ![image](https://private-user-images.githubusercontent.com/70315473/329156808-bdad8903-d2e8-4c7e-bc8f-aaa00d184678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzg2OTQsIm5iZiI6MTcxNTIzODM5NCwicGF0aCI6Ii83MDMxNTQ3My8zMjkxNTY4MDgtYmRhZDg5MDMtZDJlOC00YzdlLWJjOGYtYWFhMDBkMTg0Njc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA3MDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YmRmMTgzZGRjMTY3YzI0MmM1MzRkNDY2MTcyODI3YTVkMTMwZmJiYjNjMWNlOGMwYTFlZGUyM2M1Yjg1OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dlv1_5lcqLtykz7kl85Wbj3XHA5SqORP4xERLCd3Uxs)

ок, в этот раз прощаю

2024-05-10 05:36 UTC, closed without merging