Feat/UI components pt#3
atls/team-management pull request #13
Opened 2024-05-10 05:53 UTC by effektivnayarabota1

# в ветке 2 крайних коммита по компоненту `switch`. какой вариант корректнее?

# 1й вариант 
скопировал с [`heperion: ui-proto/switch`](https://github.com/atls/hyperion/tree/master/ui-proto/switch)
был баг в анимации, сыпались ошибки. перебирать не стал - уточняю, стоит ли тратить на это время

# 2й вариант
подсмотрел как делает @bbulakh - добавил пакет в [`index.ts`](https://github.com/atls/team-management/blob/feat/ui-components_pt%233/ui/switch/src/index.ts)
в интерфейсе все красиво но не понимаю как вносить изменения в такой компонент

---

также switch находил в [`drum-in`](https://github.com/torin-asakura/drum-in/tree/master/ui/switch), не понимаю откуда там берется сам `switch`. `active provider` понятно что делает, но где сама верстка компонента, или подключенный пакет в файлах. как это рабтает?

2024-05-10 06:44 UTC, Nelfimov requested changes
Оба варианта верные но в контексте. 

1 подходит если тебе нужен кастомный свитч, стилизация которого не подойдет используя пропсы стандартного в Hyperion. 

2 подойдёт если тебе достаточно кастомизации через пропсы. 

В drumin switch написан с нуля потому что там он «уникальный» по стилям

2024-05-14 11:37 UTC, effektivnayarabota1 commented
@Nelfimov 
подскажи пожалуйста как закинуть пропс во вложенный компонент (children). на его месте будет находиться иконка и я хочу передать в неё пропс цвета. (black white написал для теста)

https://github.com/atls/team-management/blob/feat/ui-components_pt%233/ui/switch/src/icon/thumb/thumb.element.tsx

и как обозначить на самой иконке, какая её часть будет меняться?
если делать экспорт белой иконки с прозрачным фоном (для сохранения габаритов), а цвет менять только у тумблера (как это и сделанно сейчас) - так будет корректно?

![image](https://github.com/atls/team-management/assets/70315473/d4ef783b-4e5f-430c-ac90-a74123c098dd)

в макете вот так:
![image](https://github.com/atls/team-management/assets/70315473/bc58218b-b91b-4883-b83d-36f3b8041cf3)

2024-05-14 11:43 UTC, effektivnayarabota1 commented
мне нужно чтобы иконка всегда была белой. нужно будет каждый раз добавлять `пропс цвета на верстке `или на `уровне компонтетов` это можно зафиксировать? не понимаю как в `children закинуть пропс`. так бы зафиксировал его в `тумблере`

2024-05-14 11:45 UTC, Nelfimov commented
@effektivnayarabota1 вот этот файл меняет цвет иконки после генерации.

https://github.com/torin-asakura/drum-in/blob/master/ui/icons/replacements.ts

2024-05-15 03:45 UTC, effektivnayarabota1 commented
выкидывает ошибку типов при `yarn check`, посмотри пожалуйста - не могу понять

2024-05-15 03:59 UTC, effektivnayarabota1 commented
из `hyperion` добавляю `Box`, выбрасывает предупреждение:
`Warning: Styled(div): Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`
## его можно както отключить? весь лог перекрывает, там большая пачка в три экрана.

2024-05-15 05:42 UTC, Nelfimov commented
> из `hyperion` добавляю `Box`, выбрасывает предупреждение: `Warning: Styled(div): Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`
> 
> ## его можно както отключить? весь лог перекрывает, там большая пачка в три экрана.

Это предупреждение на будущее, ошибкой не считается.

2024-05-15 05:43 UTC, Nelfimov commented
> выкидывает ошибку типов при `yarn check`, посмотри пожалуйста - не могу понять вот такой поинт обнаружил: `@emotion/react is listed by your project with version 11.9.3, which doesn't satisfy what @ui/dropdown (p2b4b6) and other dependencies request (11.11.3).`
> 
> мне нужно поставить одинаковую версию на всех компонентах? или чтобы совпадала версия в `dev` и `peer`

Так то это ошибка не критичная, тем не менее лучше наводить порядок сразу. Нужно поставить версию, которую требует пакет.

в `peer` проще ставить "*" если ты конечно не делаешь библиотеку, где важно указать версию.

2024-05-15 13:46 UTC, effektivnayarabota1 commented
### несколько вопросов:
#### 1. Как делать модалку с точки зрения _семантики_? 
по моей логике она должна быть вложенна в триггерный контейнер, но у меня так сделать не получилось. функция `onClick` передавалась всем дочерним элементам и получается так, что _при клике на само модальное окно или вложенный элемент_, напрмер `Input`, оно закрывается, поэтому сделал вот так:
```typescript
<div onClick={modalClickHandler} style={{width: 400, height: 300, backgroundColor: 'red'}}>
    <h1>click to show modal</h1>
</div>
<Modal open={modal} onClose={modalClickHandler}>
    <h1>content in modal</h1>
    <Input placeholder='placeholder' />
</Modal>
```

#### 2. То, что `onClick` передается всем детям это корректное поведение? Или это моя ошибка?

#### 3. Как делать `handler` на несколько модальных окон? 
Чтобы при клике на триггерный контейнер не открывались все модалки. Мы же не создаем для каджого `Modal` свой `handler`?
Подскажи пожалуйста как этот функционал называется, что мне почитать.

---

P.S. Мне осталось стилизовать `dropdown`, сегодня закончу.

2024-05-15 14:56 UTC, Nelfimov commented
> ### несколько вопросов:
> #### 1. Как делать модалку с точки зрения _семантики_?
> по моей логике она должна быть вложенна в триггерный контейнер, но у меня так сделать не получилось. функция `onClick` передавалась всем дочерним элементам и получается так, что _при клике на само модальное окно или вложенный элемент_, напрмер `Input`, оно закрывается, поэтому сделал вот так:
> 
> ```ts
> <div onClick={modalClickHandler} style={{width: 400, height: 300, backgroundColor: 'red'}}>
>     <h1>click to show modal</h1>
> </div>
> <Modal open={modal} onClose={modalClickHandler}>
>     <h1>content in modal</h1>
>     <Input placeholder='placeholder' />
> </Modal>
> ```

Посмотри что такое stopPropogation, а так же bubbling в веб разработке. 

> #### 2. То, что `onClick` передается всем детям это корректное поведение? Или это моя ошибка?

См выше. 

> #### 3. Как делать `handler` на несколько модальных окон?
> Чтобы при клике на триггерный контейнер не открывались все модалки. Мы же не создаем для каджого `Modal` свой `handler`? Подскажи пожалуйста как этот функционал называется, что мне почитать.

Только разделяя на фрагменты или с помощью контекстов - у каждого должен быть инициализирован свой хэндлер

2024-05-16 13:44 UTC, Nelfimov commented
> Была ошибка типов - не совпадала версия пакета `@types/react` По всем компонентам прошелся, поставил `единую версию`, `peerDeps - *`, не помогло. Нагуглил такое решение: в корневом `package.json`
> 
> ```json
> "resolutions": {
>     "@types/react": "18.3.1"
> }
> ```

Сначала попробуй через `yarn upgrade-interactive` забампить версию по всему проекту. 

Затем можешь попробовать `yarn dedupe`

Если не выйдет - тогда можешь пользоваться резолюшенами.

2024-05-16 14:44 UTC, effektivnayarabota1 commented
> Сначала попробуй через `yarn upgrade-interactive` забампить версию по всему проекту.

Готово! Жду ревью

2024-05-16 15:40 UTC, Nelfimov requested changes

2024-05-16 15:40 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/page.tsx
> +const Page = () => {
понимаю что ты так тестировал верстку. Но это не должно попадать в мастер. Максимум оставить тему.

2024-05-16 15:40 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/page.tsx
> +        <div>{dropdownItem}</div>
"родные" html теги в нашем коде не используются. Никаких `div`, `span` и прочее

2024-05-16 15:40 UTC, Nelfimov commented on app/entrypoints/renderer/package.json
> +    "@ui/dropdown": "workspace:*",
перенеси все локальные зависимости в `devDependencies` - у нас деплой потом не сработает

2024-05-16 15:40 UTC, Nelfimov commented on ui/modal/src/container/container.styles.ts
> +  zIndex: 1300,
`magic number`

2024-05-16 15:40 UTC, Nelfimov commented on ui/modal/src/child-container/child-container.styles.ts
> +  padding: '12px 24px',
числа и калькуляции - из темы

2024-05-16 15:40 UTC, Nelfimov commented on ui/modal/src/child-container/child-container.styles.ts
> +  backgroundColor: 'rgba(255, 255, 255, 1)',
из темы

2024-05-16 15:40 UTC, Nelfimov commented on ui/modal/src/backdrop/backdrop.styles.ts
> +  backgroundColor: 'rgba(0, 0, 0, 0.5)',
тут позволительно взять из объекта темы. А можно вытягивать тему из родительского компонента и сюда как пропс передавать

2024-05-16 15:40 UTC, Nelfimov commented on ui/switch/package.json
> +    "framer-motion": "10.16.1",
версии

2024-05-16 15:40 UTC, Nelfimov commented on ui/switch/src/base/base.component.tsx
> +const BaseSwitch = ({ disabled, checked: defaultValue, onChange }: BaseSwitchProps) => {
1. много объектов в одном файле. Раскидывай по своим
2. интерфейс делай через `FC`

2024-05-16 15:40 UTC, Nelfimov commented on ui/switch/src/icon/icon.component.tsx
> +const IconSwitch = ({ disabled, checked: defaultValue, onChange, children }: IconSwitchProps) => {
1. много объектов
2. через `FC`

2024-05-16 15:40 UTC, Nelfimov commented on ui/switch/src/index.ts
> +export * from './theme'
нейминги - добавь `-switch`

2024-05-16 16:10 UTC, effektivnayarabota1 commented on package.json
> +    "@types/react": "^18.3.2",
+

2024-05-16 16:25 UTC, effektivnayarabota1 commented on ui/icons/src/TestIcon.tsx
> +import { useTheme } from '@emotion/react'
этот компонент вручную сколотил для теста, иконками богдан занимался.

2024-05-16 16:43 UTC, Nelfimov commented on ui/icons/src/TestIcon.tsx
> +import { useTheme } from '@emotion/react'
На будущее - иконки делаем через генератор.

2024-05-16 17:08 UTC, effektivnayarabota1 commented on ui/dropdown/src/child-container/child-container.styles.ts
> +  padding: 10,
в `theme` можно добавлять файлы?

2024-05-16 17:08 UTC, effektivnayarabota1 commented on ui/dropdown/src/child-container/child-container.styles.ts
> +  padding: 10,
`paddings` создам или `sizes`

2024-05-16 17:15 UTC, effektivnayarabota1 commented on ui/modal/src/modal.interfaces.ts
> +  onClose?: (e: any) => void
а где можно посмотреть стандартные типы? 
`VoidFunction` - этот не отгуглил например. в драм ине нашел

2024-05-16 17:16 UTC, Nelfimov commented on ui/dropdown/src/child-container/child-container.styles.ts
> +  padding: 10,
Можешь spaces

2024-05-16 17:17 UTC, Nelfimov commented on ui/modal/src/modal.interfaces.ts
> +  onClose?: (e: any) => void
Такое только искать в документации typescript или из опыта.

2024-05-16 17:20 UTC, effektivnayarabota1 commented on ui/modal/src/child-container/child-container.styles.ts
> +  right: 0,
дополнительный файл в тему добавлю `positions.ts`?

2024-05-16 17:26 UTC, Nelfimov commented on ui/modal/src/child-container/child-container.styles.ts
> +  right: 0,
Можно так же spaces

2024-05-16 17:27 UTC, Nelfimov commented on ui/modal/src/child-container/child-container.styles.ts
> +  padding: '12px 24px',
Spaces

2024-05-16 17:34 UTC, effektivnayarabota1 commented on ui/dropdown/src/button/button.component.tsx
> +      <Dot />
`[ДОТ ДОТ ДОТ]?`

2024-05-16 17:34 UTC, effektivnayarabota1 commented on ui/dropdown/src/button/button.component.tsx
> +      <Dot />
`+ map?`

2024-05-16 17:38 UTC, Nelfimov commented on ui/theme/package.json
> +  "main": "src/index.ts",
Должен быть один подход. Можешь использовать оба, они не взаимоисключающие

2024-05-16 17:40 UTC, Nelfimov commented on ui/dropdown/src/button/button.component.tsx
> +      <Dot />
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

2024-05-17 08:16 UTC, effektivnayarabota1 commented on ui/dropdown/src/button/button.interfaces.ts
> +  triggerProps: object
`интерфейс` должен обязательно расширять какойто `базовый тип`?
мой компонент использует всего три свойства - могу ли я создать `новый интерфейс` включающий только эти свойства, не расширяя базовый

2024-05-17 08:50 UTC, Nelfimov commented on ui/dropdown/src/button/button.interfaces.ts
> +  triggerProps: object
да. Используем только необходимое. Излишество излишне

2024-05-17 20:37 UTC, effektivnayarabota1 commented
🙏🙏🙏🙏🙏🙏🙏 https://github.com/atls/team-management/issues/11#issuecomment-2118351193

2024-05-20 06:33 UTC, Nelfimov requested changes

2024-05-20 06:33 UTC, Nelfimov commented on .yarnrc.yml
> +packageExtensions:
нужно ли это теперь здесь?

2024-05-20 06:33 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/page.tsx
> +const Page = () => <ThemeProvider>page</ThemeProvider>
1. `ThemeProvider` в `layout.tsx`
2. "page" не нужен

2024-05-20 06:33 UTC, Nelfimov commented on ui/modal/src/child-container/child-container.styles.ts
> +  maxWidth: 'calc(100% - 24px)',
`calc` в константу рядом

2024-05-20 06:33 UTC, Nelfimov commented on ui/modal/src/child-container/child-container.styles.ts
> +  padding: '12px 24px',
из темы

2024-05-20 06:33 UTC, Nelfimov commented on ui/modal/src/child-container/child-container.styles.ts
> +  width: '486px',
в константу

2024-05-20 06:33 UTC, Nelfimov commented on ui/modal/src/modal.component.tsx
> +  const childrenContainerHandler = (e) => {
упустил

2024-05-20 06:33 UTC, Nelfimov commented on ui/modal/src/modal.component.tsx
> +const Modal: FC<ModalProps> = ({ children, open }) => {
`PropsWithChildren`

2024-05-20 06:33 UTC, Nelfimov commented on ui/modal/src/modal.interfaces.ts
> +  children: JSX.Element
лишнее если `PropsWithChildren`

2024-05-20 06:33 UTC, Nelfimov commented on ui/input/src/input.styles.ts
> +  fontWeight: 400,
тоже можно из темы взять

2024-05-20 06:33 UTC, Nelfimov commented on ui/input/package.json
> +  "dependencies": {
генератором не желаешь воспользоваться?

2024-05-20 06:33 UTC, Nelfimov commented on ui/icons/package.json
> +  "devDependencies": {
где же генератор?

2024-05-20 06:33 UTC, Nelfimov commented on ui/dropdown/src/button/dot/dot.component.tsx
> +  const dotsCount = 3
вынеси в пропсы - тогда сможешь настраивать в родительских компонентах

2024-05-20 06:33 UTC, Nelfimov commented on ui/dropdown/src/button/dot/dot.component.tsx
> +export const DotComponent: FunctionComponent<any> = () => {
`any`

2024-05-20 06:33 UTC, Nelfimov commented on ui/dropdown/src/button/button.interfaces.ts
> +  triggerProps: object
не поправил

2024-05-20 06:33 UTC, Nelfimov commented on ui/dropdown/src/button/button.styles.ts
> +  gap: 3,
тема

2024-05-20 06:33 UTC, Nelfimov commented on ui/dropdown/src/child-container/child-container.component.tsx
> +  const childrenContainerHandler = (e) => {
интерфейс

2024-05-20 06:33 UTC, Nelfimov commented on ui/dropdown/src/child-container/child-container.interfaces.ts
> +  layerProps: object
без изменений

2024-05-20 06:33 UTC, Nelfimov commented on ui/dropdown/src/child-container/child-container.component.tsx
> +export const ChildContainer: FC<ChildContainerProps> = ({ layerProps, children }) => {
`PropsWithChildren`

2024-05-20 07:40 UTC, effektivnayarabota1 commented on .yarnrc.yml
> +packageExtensions:
без этого ошибки на `тайпчеке`:
```
➤ YN0000: ┌ Typecheck
➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-input-virtual-93844aacd4/0/cache/@atls-ui-parts-input-npm-0.1.1-e57d4e695f-000f82aad0.zip/node_modules/@atls-ui-parts/input/dist/input/r
➤ YN0000: │ aw-input.component.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find type definition file for 'react'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-switch-virtual-24fd0c36a9/0/cache/@atls-ui-parts-switch-npm-0.1.1-8284bcc81f-af1c1b0781.zip/node_modules/@atls-ui-parts/switch/dist/hand
➤ YN0000: │ le/handle.component.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find type definition file for 'react'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-switch-virtual-24fd0c36a9/0/cache/@atls-ui-parts-switch-npm-0.1.1-8284bcc81f-af1c1b0781.zip/node_modules/@atls-ui-parts/switch/dist/hand
➤ YN0000: │ le/handle.element.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find type definition file for 'react'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: └ Completed in 7s 776ms
```

2024-05-20 08:02 UTC, effektivnayarabota1 commented on ui/dropdown/src/child-container/child-container.component.tsx
> +export const ChildContainer: FC<ChildContainerProps> = ({ layerProps, children }) => {
все интерфейсы у которых будет `children` называть `PropsWithChildren`?

2024-05-20 08:04 UTC, Nelfimov commented on ui/dropdown/src/child-container/child-container.component.tsx
> +export const ChildContainer: FC<ChildContainerProps> = ({ layerProps, children }) => {
Надо оборачивать интерфейсы в этот интерфейс. Например:

```tsx
const Component: FC<PropsWithChildren<ComponentProps>> = ({ children, props }) => <div>{children}</div>
```

2024-05-20 10:35 UTC, effektivnayarabota1 commented on ui/input/package.json
> +  "dependencies": {
какие компоненты мы еще можем генерировать помимо `иконок` и `инпута`?

2024-05-20 10:49 UTC, Nelfimov commented on ui/dropdown/src/button/button.styles.ts
> +  gap: 3,
только числа.

2024-05-20 10:50 UTC, Nelfimov commented on ui/dropdown/src/button/button.styles.ts
> +  gap: 3,
> я могу в объект baseButtonStyles возвращать ...theme.spaces.dropdown.button, чтобы каждое отдельное свойство не подключать?

Лучше явно указывать.

2024-05-20 10:51 UTC, Nelfimov commented on ui/input/package.json
> +  "dependencies": {
https://github.com/atls/hyperion/tree/master/generators

2024-05-20 11:18 UTC, effektivnayarabota1 commented on app/entrypoints/renderer/src/app/page.tsx
> +const Page = () => <ThemeProvider>page</ThemeProvider>
линтер не пропускает пустой `jsx`

2024-05-20 12:49 UTC, Nelfimov requested changes
форс пушить после ревью - запрещено.

2024-05-20 12:49 UTC, Nelfimov commented on app/entrypoints/renderer/package.json
> +    "@ui/switch": "workspace:*",
лишние зависимости убери отсюда

2024-05-20 14:05 UTC, effektivnayarabota1 commented on ui/theme/src/theme/spaces.ts
> +export const spaces = {
`колорс` и `спейсес` сделанны идентично. я оба файла правлю, правильно?

2024-05-20 14:05 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +export const spaces = {
`colors` можешь не трогать - там обусловлено генераторами.

2024-05-21 06:49 UTC, Nelfimov requested changes
генератор иконок был старой версии. Обновил зависимости и поправил запуск. Перегенерировал иконки

2024-05-21 06:49 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/layout.tsx
> +  <ThemeProvider>
`ThemeProvider` опусти в `body` - иначе семантически у тебя странно выходит, что контент страницы вышел за html

2024-05-21 06:49 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +  count: {
контекст

2024-05-21 06:49 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +  sizes: {
так же привязался к контекстам

2024-05-21 06:49 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +    modalChildContainerMaxHeight: 'calc(100% - 24px)',
это и выше - дубликаты

2024-05-21 06:49 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +  defaultPadding: '12px 24px',
не стоит дефолтным обзывать - все таки дефолта в проекта нет

2024-05-21 06:49 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +  s0: 0,
`zero`

2024-05-21 08:09 UTC, effektivnayarabota1 commented on ui/theme/src/theme/spaces.ts
> +    modalChildContainerMaxHeight: 'calc(100% - 24px)',
дубликаты ты имеешь ввиду в наименовании?

2024-05-21 08:11 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +    modalChildContainerMaxHeight: 'calc(100% - 24px)',
нет, в значениях. Мы же поэтому переносим все в тему - чтобы по уникальному названию подставить необходимый аттрибут. А тут у тебя в обоих случаях `calc(100% - 24px)`

2024-05-21 08:11 UTC, effektivnayarabota1 commented on ui/theme/src/theme/spaces.ts
> +  sizes: {
контекста `count` недостаточно? привязываться к `компонентам`?

2024-05-21 08:12 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +    modalChildContainerMaxHeight: 'calc(100% - 24px)',
ну и на всякий случай - не должно быть привязки к контексту. Ни к названию компонента, ни к названию аттрибута (width, height). Чисто уникальное название, например `fullWidthWithPaddingSmall`

2024-05-21 10:26 UTC, Nelfimov requested changes

2024-05-21 10:26 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +  fixed: 'fixed',
так, `fixed`, `flex`, `pointer`, `min-content` и прочие:
1. являются дефолтными css аттрибутами
2. не подходят под `spaces`

Убираем.

2024-05-21 10:26 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +  semiTiny: 3,
дубликат с `s3`

2024-05-21 10:26 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +  semiRegular: 18,
дубликат

2024-05-21 10:26 UTC, Nelfimov commented on ui/theme/src/theme/spaces.ts
> +  tiny: 10,
дубликат

2024-05-22 05:11 UTC, Nelfimov approved these changes

2024-05-22 05:11 UTC, merged