feat: UI-components
atls/team-management pull request #15
Opened 2024-05-16 15:21 UTC by bbulakh

Closes https://github.com/atls/team-management/issues/14

2024-05-16 15:53 UTC, Nelfimov commented on ui/checkbox/package.json
> +    "@ui/icons": "workspace:*",
в обычные зависимости

2024-05-16 15:53 UTC, Nelfimov commented on ui/checkbox/src/checkbox.component.tsx
> +export const Checkbox: FC<CheckboxProps> = ({
каждому объекту - свой файл

2024-05-16 15:54 UTC, Nelfimov commented on ui/checkbox/src/checkbox.component.tsx
> +      <Check checked={checked}>{checked && <CheckIcon width={20} height={20} />}</Check>
посмотри на гиперионовский `Condition`

2024-05-16 15:54 UTC, Nelfimov commented on ui/checkbox/src/checkbox.interface.ts
> +  onCheck?: (newState: boolean) => any
`any` нельзя. Если не знаешь - пока `void`

2024-05-16 15:55 UTC, Nelfimov commented on ui/checkbox/src/checkbox.styles.ts
> +export const boxBaseStyles = createBoxBaseStyles()
для всех аттрибутов здесь можешь взять объект темы из `@ui/theme` и переиспользовать

2024-05-16 15:56 UTC, Nelfimov commented on ui/icons/package.json
> +    "@atls-ui-generators/icons": "0.0.2",
в обычные

2024-05-16 15:56 UTC, Nelfimov commented on ui/icons/package.json
> +    "@atls-ui-generators/icons": "0.0.2",
в обычные

2024-05-16 15:56 UTC, Nelfimov commented on ui/scroll/src/scroll.component.tsx
> +const Scroll: React.FC<ScrollProps> = ({ children }) => (
в разные файлы

2024-05-16 15:56 UTC, Nelfimov commented on ui/scroll/src/scroll.interface.ts
> +export default ScrollProps
дефолтным экспортом не стоит пользоваться

2024-05-21 08:42 UTC, bbulakh commented on ui/checkbox/src/checkbox.styles.ts
> +export const boxBaseStyles = createBoxBaseStyles()
@Nelfimov, мне остаётся только этот вопрос. Я видел, что Кирилл сейчас в теме оформляет цвета, размеры и т.п. 
Вопрос к подходу - мне делать так же? Есть ощущение, что если я добавлю еще свои размеры дальше будет не удобно

<img width="424" alt="image" src="https://github.com/atls/team-management/assets/95144713/e2dd1d83-51c9-4ad9-a841-a660869b4b19">

2024-05-21 09:50 UTC, bbulakh commented on ui/checkbox/src/checkbox.component.tsx
> +      <Check checked={checked}>{checked && <CheckIcon width={20} height={20} />}</Check>
Добавил ```condition```, но линтер ругается на smooth = {true}. Без него анимация не работает. Это можно как-то пофиксить?

```
 Error: Value must be omitted for boolean attributes react/jsx-boolean-value
➤ YN0000: │ 
➤ YN0000: │   34 |         <Condition
➤ YN0000: │   35 |           match={checked}
➤ YN0000: │ > 36 |           smooth={true}
➤ YN0000: │      |           ^
➤ YN0000: │   37 |           smoothOptions={{ duration: 0.3, pattern: 'in-and-out' }}
➤ YN0000: │   38 |         >
➤ YN0000: │   39 |           <CheckIcon width={20} height={20} />

```

2024-05-21 14:10 UTC, bbulakh commented
@Nelfimov Запросил повторное ревью.

2024-05-22 05:37 UTC, Nelfimov requested changes
если ты пишешь обычный пакет в монорепе (не библиотеку для паблиша в npm) то не надо фиксировать версии в `peerDependencies`

2024-05-22 05:37 UTC, Nelfimov commented on tsconfig.json
> +  "include": ["app/**/*", "ui/**/**/**/**/*", "fragments/**/*"],
у `ui` достаточно `ui/**/*`

2024-05-22 05:37 UTC, Nelfimov commented on app/entrypoints/renderer/package.json
> +    "@ui/scroll": "workspace:*",
это и выше - не нужно в энтрипоинте

2024-05-22 05:37 UTC, Nelfimov commented on ui/checkbox/package.json
> +    "react-dom": "18.2.0",
здесь и выше - конкретные версии не нужны

2024-05-22 05:37 UTC, Nelfimov commented on ui/condition/src/index.ts
> +export * from './condition.interface'
зачем копировать код пакета если можно просто установить как зависимость и реэкспортировать?

2024-05-22 05:37 UTC, Nelfimov commented on ui/divider/src/index.ts
> +export * from './divider.component'
аналогично `Condition`

2024-05-22 05:37 UTC, Nelfimov commented on ui/icons/package.json
> +    "@atls-ui-generators/icons": "0.0.2",
не доделал - тут осталось

2024-05-22 05:37 UTC, Nelfimov commented on ui/icons/package.json
> +    "@atls-ui-generators/icons": "0.0.2",
древняя версия

2024-05-22 05:37 UTC, Nelfimov commented on ui/icons/package.json
> +    "glob": "10.3.15",
здесь и выше - версии

2024-05-22 05:37 UTC, Nelfimov commented on ui/scroll/src/scroll.styles.ts
> +  width: 100%;
высота, ширина, цвета, радиус, бордер - из темы. Для бордера можешь отдельный объект сделать `border`

2024-05-22 09:19 UTC, bbulakh commented
@effektivnayarabota1 Ты сталкивался с этими ворнами? 

```
➤ YN0060: │ @emotion/react is listed by your project with version 11.11.4, which doesn't satisfy what @atls-ui-parts/layout (p49b9d) and other dependencies request (11.11.3).
➤ YN0060: │ @emotion/styled is listed by your project with version 11.11.5, which doesn't satisfy what @atls-ui-parts/checkbox (p06858) and other dependencies request (11.11.0).
➤ YN0060: │ @emotion/styled is listed by your project with version 11.11.5, which doesn't satisfy what @atls-ui-parts/layout (p60eb1) requests (11.11.0).
➤ YN0002: │ @app/renderer-entrypoint@workspace:app/entrypoints/renderer doesn't provide glob (p81cda), requested by @ui/icons.
➤ YN0002: │ @app/renderer-entrypoint@workspace:app/entrypoints/renderer doesn't provide glob (p94b08), requested by @ui/checkbox.

```

2024-05-22 09:22 UTC, effektivnayarabota1 commented
> @effektivnayarabota1 Ты сталкивался с этими ворнами?
> 
> ```
> ➤ YN0060: │ @emotion/react is listed by your project with version 11.11.4, which doesn't satisfy what @atls-ui-parts/layout (p49b9d) and other dependencies request (11.11.3).
> ➤ YN0060: │ @emotion/styled is listed by your project with version 11.11.5, which doesn't satisfy what @atls-ui-parts/checkbox (p06858) and other dependencies request (11.11.0).
> ➤ YN0060: │ @emotion/styled is listed by your project with version 11.11.5, which doesn't satisfy what @atls-ui-parts/layout (p60eb1) requests (11.11.0).
> ➤ YN0002: │ @app/renderer-entrypoint@workspace:app/entrypoints/renderer doesn't provide glob (p81cda), requested by @ui/icons.
> ➤ YN0002: │ @app/renderer-entrypoint@workspace:app/entrypoints/renderer doesn't provide glob (p94b08), requested by @ui/checkbox.
> ```

первые три предупреждение - да, версии разъезжаются
попробуй этой командой под одну версию подогнать: `yarn upgrade-interactive`

а крайние две - это пакет не подключен. попробуй добавить `glob` в `package.json` или если рабоать не будет, то через `packageExtention`, как ты мне и рекомендовал

2024-05-22 13:39 UTC, bbulakh commented
@Nelfimov, запросил ревью.
Всё должно быть ок, но эти ворны с версиями не пропадают. Сначала я использовал ```yarn upgrade-interactive```, потом Кирилл попробовал у себя (вручную тоже пробовали). В итоге остались с этим:

```
➤ YN0060: │ @emotion/react is listed by your project with version 11.11.4, which doesn't satisfy what @atls-ui-parts/layout (p85ece) and other dependencies request (11.11.3).
➤ YN0060: │ @emotion/styled is listed by your project with version 11.11.5, which doesn't satisfy what @atls-ui-parts/checkbox (p25055) and other dependencies request (11.11.0).
➤ YN0060: │ react is listed by your project with version 18.3.1, which doesn't satisfy what @atls-ui-parts/layout (paf38f) and other dependencies request (18.2.0).
➤ YN0060: │ react-dom is listed by your project with version 18.3.1, which doesn't satisfy what @atls-ui-parts/progress (p93965) requests (18.2.0).
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
```

2024-05-23 05:23 UTC, Nelfimov approved these changes

2024-05-23 05:24 UTC, merged