Feat/fragments user card users grid
atls/team-management pull request #21
Opened 2024-05-30 23:58 UTC by ssagg

Added User Card and User Grid

2024-06-05 06:15 UTC, Nelfimov requested changes
1. везде расставить `type: module` и `private: true`
2. хороший подход к типизации темы. Можно еще так:

```tsx
/* theme.provider.tsx */

import React                                     from 'react'

import { ThemeProvider as EmotionThemeProvider } from '@emotion/react'

import { ThemeProviderProps }                    from './theme.interfaces'
import { borders }                               from './theme'
import { colors }                                from './theme'
import { fontFamily }                            from './theme'
import { fontSize }                              from './theme'
import { fontWeight }                            from './theme'
import { radii }                                 from './theme'

const theme = {
  colors,
  fontSize,
  fontWeight,
  fontFamily,
  radii,
  borders,
}

export type ThemeType = typeof theme
```

2024-06-05 06:15 UTC, Nelfimov commented on app/fragments/app-animated-card/src/animated-card.component.tsx
> +            Вы уверены, что хотите исключить пользователя из данной организации?
локаль - используй `useIntl` -> `FormattedMessage`

2024-06-05 06:15 UTC, Nelfimov commented on app/fragments/app-animated-card/src/animated-card.component.tsx
> +              setOpenMenu(false)
для читаемости лучше вынести в тело

2024-06-05 06:15 UTC, Nelfimov commented on app/fragments/app-users-grid/src/users-grid.component.tsx
> +    <Box display='grid' gridTemplateColumns='repeat(3,407px)' gap={theme.spaces?.semiLarge}>
в идеале это в тему

2024-06-05 06:15 UTC, Nelfimov commented on app/fragments/app-users-modal/src/users-modal.component.tsx
> +    <Modal open={true} width={theme.spaces?.extraLargeDecreased} padding={theme.spaces?.increased}>
`open=true` всегда?

2024-06-05 06:15 UTC, Nelfimov commented on ui/image/src/image-block/image-block.component.tsx
> +const Image = styled.img<ContainerProps>(createBaseImageBlockStyles())
рассмотри `next-image` раз уж мы на нексте https://github.com/atls/hyperion/tree/master/ui-parts/next-image

2024-06-05 06:15 UTC, Nelfimov commented on ui/tag/src/tag.component.tsx
> +      // flexDirection={flexDirection}
закоменченный код

2024-06-07 07:04 UTC, Nelfimov requested changes
чеки и конфликты

2024-06-07 18:54 UTC, ssagg commented
@Nelfimov что-то закопался. но вроде пофиксил

2024-06-10 07:43 UTC, Nelfimov approved these changes

2024-06-10 07:44 UTC, Nelfimov approved these changes

2024-06-10 07:47 UTC, Nelfimov approved these changes

2024-06-10 07:50 UTC, merged