Feat/fragments
atls/team-management pull request #22
Opened 2024-06-04 06:39 UTC by effektivnayarabota1

2024-06-04 08:05 UTC, Nelfimov requested changes
1. дублировать замечания не стал - на примере моих замечаний посмотри остальные фрагменты
2. пока далеко не ушли - переведи все пакеты в `esm`

2024-06-04 08:05 UTC, Nelfimov commented on app/fragments/add-member-modal/src/input/check-valid-email.utils.ts
> +export const checkValidEmail = (inputValue: string) =>
это можно в `/utils/validators` вынести как отдельный пакет

2024-06-04 08:05 UTC, Nelfimov commented on app/fragments/add-member-modal/src/input/input.component.tsx
> +  const handleInputDelete = () => {
1. логику в отдельный хук
2. интерфейсы

2024-06-04 08:05 UTC, Nelfimov commented on app/fragments/add-member-modal/src/input/input.component.tsx
> +      if (!isEmailValid) setErrorText('Введите правильный E-mail')
локали не должно быть в коде - используй `useIntl`

2024-06-04 08:05 UTC, Nelfimov commented on app/fragments/add-member-modal/src/add-member-modal.component.tsx
> +  const theme: any = useTheme()
проверь нужна ли тебе здесь тема - по логике должно парсится из строки типа `spaces.increased`

2024-06-04 08:05 UTC, Nelfimov commented on app/fragments/organization-card/src/organization-card.component.tsx
> +  if (quantity === 1) memberString = 'member'
`useIntl` - изучи. Там есть функционал работы с кол-вом

2024-06-04 08:05 UTC, Nelfimov commented on app/fragments/organization-card/src/organization-card.component.tsx
> +        {quantity} {memberString}
для пробелов есть отдельный компонент `Space` в гиперионе

2024-06-04 08:05 UTC, Nelfimov commented on app/fragments/organization-card/src/organization-card.component.tsx
> +    <Box minWidth={150}>
`magic number`

2024-06-04 08:05 UTC, Nelfimov commented on app/fragments/organization-card/src/organization-card.styles.ts
> +import { styleFn } from 'styled-system'
во фрагментах стилей не должно быть

2024-06-04 08:05 UTC, Nelfimov commented on app/fragments/organization-card-grid/src/organization-card-grid.component.tsx
> +  <GridAutoRows rowHeight={150} columns={2} maxColumnWidth={620}>
`magic numbers`

2024-06-04 09:28 UTC, effektivnayarabota1 commented on app/fragments/add-member-modal/src/add-member-modal.component.tsx
> +  const theme: any = useTheme()
строка не изменила внешний вид
![image](https://github.com/atls/team-management/assets/70315473/67757423-06bc-4fff-a36e-0f2a2f8fb3a6)

2024-06-04 09:40 UTC, effektivnayarabota1 commented on app/fragments/add-member-modal/src/add-member-modal.component.tsx
> +  const handleAddInputClick = () => {
рядом, ты имеешь ввиду в файле `...hook.ts`?

2024-06-04 09:40 UTC, Nelfimov commented on app/fragments/add-member-modal/src/add-member-modal.component.tsx
> +  const handleAddInputClick = () => {
да

2024-06-05 06:06 UTC, Nelfimov requested changes
1. интерфейсы в функциях
2. `type: module`
3. Для интерфейса темы чтобы не использовать `any` можешь сделать такую штуку:

```ts
/* theme.provider.tsx */
import React                                     from 'react'

import { ThemeProvider as EmotionThemeProvider } from '@emotion/react'

import { ThemeProviderProps }                    from './theme.interfaces'
import { borders }                               from './theme'
import { colors }                                from './theme'
import { fontFamily }                            from './theme'
import { fontSize }                              from './theme'
import { fontWeight }                            from './theme'
import { radii }                                 from './theme'

const theme = {
  colors,
  fontSize,
  fontWeight,
  fontFamily,
  radii,
  borders,
}

export type ThemeType = typeof theme
```

2024-06-05 08:54 UTC, effektivnayarabota1 commented on app/fragments/add-member-modal/src/input/input.component.tsx
> +      if (!isEmailValid) setErrorText(formatMessage({ id: 'add-member-modal_input.invalid-email' }))
у меня вормат не правит этот стиль

2024-06-05 09:25 UTC, Nelfimov commented on app/fragments/add-member-modal/src/input/input.component.tsx
> +      if (!isEmailValid) setErrorText(formatMessage({ id: 'add-member-modal_input.invalid-email' }))
тогда вручную

2024-06-05 11:08 UTC, effektivnayarabota1 commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
не понимаю, откуда `yarn` читает `tsconfig`
при установке `type: module`, ругается на то, что нет расширения у импортов
хочу поменять `Module Resolution` на `bundler`, но при изменении в корне - ошибка не уходит.

2024-06-05 11:09 UTC, effektivnayarabota1 commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
выглядит так, как будто конфиг не меняется

2024-06-05 13:41 UTC, ssagg commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
> не понимаю, откуда `yarn` читает `tsconfig` при установке `type: module`, ругается на то, что нет расширения у импортов хочу поменять `Module Resolution` на `bundler`, но при изменении в корне - ошибка не уходит.



> не понимаю, откуда `yarn` читает `tsconfig` при установке `type: module`, ругается на то, что нет расширения у импортов хочу поменять `Module Resolution` на `bundler`, но при изменении в корне - ошибка не уходит.



> не понимаю, откуда `yarn` читает `tsconfig` при установке `type: module`, ругается на то, что нет расширения у импортов хочу поменять `Module Resolution` на `bundler`, но при изменении в корне - ошибка не уходит.

Я в корне поменял. Ошибки ушли. Ну или расширения добавлять везде.
![Screenshot from 2024-06-05 10-40-36](https://github.com/atls/team-management/assets/104500533/75dc45f9-8a7f-47da-bdab-da37be95aedb)

2024-06-05 13:46 UTC, Nelfimov commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
Добавь расширения у импортов.

2024-06-05 13:47 UTC, Nelfimov commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
в бандле свой встроенный tsconfig - его ты можешь только частично "модифицировать" из проекта.

https://github.com/atls/tools/blob/master/config/typescript/src/config.ts

2024-06-05 14:24 UTC, effektivnayarabota1 commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
> > не понимаю, откуда `yarn` читает `tsconfig` при установке `type: module`, ругается на то, что нет расширения у импортов хочу поменять `Module Resolution` на `bundler`, но при изменении в корне - ошибка не уходит.
> 
> > не понимаю, откуда `yarn` читает `tsconfig` при установке `type: module`, ругается на то, что нет расширения у импортов хочу поменять `Module Resolution` на `bundler`, но при изменении в корне - ошибка не уходит.
> 
> > не понимаю, откуда `yarn` читает `tsconfig` при установке `type: module`, ругается на то, что нет расширения у импортов хочу поменять `Module Resolution` на `bundler`, но при изменении в корне - ошибка не уходит.
> 
> Я в корне поменял. Ошибки ушли. Ну или расширения добавлять везде. ![Screenshot from 2024-06-05 10-40-36](https://private-user-images.githubusercontent.com/104500533/336861687-75dc45f9-8a7f-47da-bdab-da37be95aedb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTc2ODQsIm5iZiI6MTcxNzU5NzM4NCwicGF0aCI6Ii8xMDQ1MDA1MzMvMzM2ODYxNjg3LTc1ZGM0NWY5LThhN2YtNDdkYS1iZGFiLWRhMzdiZTk1YWVkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxNDIzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjQ0MGM2OGU4YzVhMWZlNjM4ZmE4Y2QyMWEwOWJkODZiOGJmZjNhZDRkMjA4NmQ1NzU4YTQyNzBiNmFjMTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A7rMh5N19KRxJacOmghz5r2S6Ubnwgu_sYQVr5o8gys)

@ssagg можешь ветку запушить? у меня вообще не работает никак. конфиг не меняет ничего, при указании расширения - другая ошибка лезет, которая просит изменения в конфиге

2024-06-05 14:45 UTC, Nelfimov commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
Покажи ошибки

2024-06-05 14:51 UTC, effektivnayarabota1 commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
```ts
export * from './email.validator'
```
```
➤ YN0000: │ ui/utils/src/validators/index.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find module './email.validator' or its corresponding type declarations.
```


---


```ts
export * from './email.validator.ts'
```
```
➤ YN0000: │ ui/utils/src/validators/index.ts
➤ YN0000: │ 
➤ YN0000: │   Error: An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.
```

2024-06-05 14:53 UTC, Nelfimov commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
нужно `.js` расширение в импорт добавлять

2024-06-05 14:54 UTC, effektivnayarabota1 commented on app/fragments/organization-card-grid/package.json
> +  "license": "BSD-3-Clause",
> нужно `.js` расширение в импорт добавлять

🤦‍♂️

2024-06-05 16:44 UTC, effektivnayarabota1 commented on app/fragments/add-member-modal/src/update-input-values.hook.ts
> +export const useUpdateInputValuesHook = (inputValues, setInputValues) => (inputIndex, value) => {
по моей логике вообще `useEffect` и вложенного в компонент `setState` было бы достоточно - **и так работало.** 
TS жаловался, просил обернуть в `useCallback` это все, я начал городить. 
`TS` не жалуется и работает.

2024-06-05 16:49 UTC, Nelfimov commented on app/fragments/add-member-modal/src/update-input-values.hook.ts
> +export const useUpdateInputValuesHook = (inputValues, setInputValues) => (inputIndex, value) => {
а на что жаловался ts?

2024-06-05 16:58 UTC, effektivnayarabota1 commented on app/fragments/add-member-modal/src/update-input-values.hook.ts
> +export const useUpdateInputValuesHook = (inputValues, setInputValues) => (inputIndex, value) => {
кажется вот эта 
`React Hook useEffect has a missing dependency: 'parentHook'.`
завтра по коммитам откачусь, посмотрю, если есть промежуточные варианты.

2024-06-05 17:21 UTC, Nelfimov commented on app/fragments/add-member-modal/src/update-input-values.hook.ts
> +export const useUpdateInputValuesHook = (inputValues, setInputValues) => (inputIndex, value) => {
Так это же линтер. Он тебе говорит о неправильности стиля кода. 

Но если ты уверен что поступаешь правильно - можешь добавить в игнор для этой строки.

2024-06-05 17:24 UTC, effektivnayarabota1 commented on app/fragments/add-member-modal/src/update-input-values.hook.ts
> +export const useUpdateInputValuesHook = (inputValues, setInputValues) => (inputIndex, value) => {
путаница была с хуками, калбэками. завтра скину как я вижу этот функционал, попрошу фидбэк

2024-06-06 06:08 UTC, Nelfimov commented on app/fragments/add-member-modal/package.json
> +  "license": "BSD-3-Clause",
упустил?

2024-06-06 07:03 UTC, effektivnayarabota1 commented
> изменений в коде после ревью нет

збыл ветки слить. обновился

2024-06-06 08:03 UTC, Nelfimov commented on app/fragments/add-member-modal/src/input/input.component.tsx
> +      if (!isEmailValid) setErrorText(formatMessage({ id: 'add-member-modal_input.invalid-email' }))
не исправлено

2024-06-06 08:04 UTC, Nelfimov commented on app/fragments/add-member-modal/src/update-input-values.hook.ts
> +export const useUpdateInputValuesHook = (inputValues, setInputValues) => (inputIndex, value) => {
без изменений

2024-06-06 12:58 UTC, effektivnayarabota1 commented
@Nelfimov rewiew request

2024-06-06 14:46 UTC, effektivnayarabota1 commented
👀

2024-06-07 07:03 UTC, Nelfimov approved these changes

2024-06-07 07:03 UTC, merged