Feat/pages users
atls/team-management pull request #27
Opened 2024-06-12 02:23 UTC by ssagg

- https://github.com/atls/team-management/issues/24
Сделана анимация сайдбара и layout страницы.
Нужно сделать модалки команды и уведомлений.

2024-06-12 02:51 UTC, ssagg commented
@effektivnayarabota1 в этом ПР сделал анимацию сайдбара и чтобы он прилипал. Надо будет глобальные стили обсудить, все ли свойства там нужны.

2024-06-12 06:30 UTC, effektivnayarabota1 commented
> @effektivnayarabota1 в этом ПР сделал анимацию сайдбара и чтобы он прилипал. Надо будет глобальные стили обсудить, все ли свойства там нужны.

ты хочешь вычистить неиспользуемые?

по `переключателю темы` сегодня правки внесу. на темной теме используется только файл `colors`, остальные - общие, в общие и вынесу чтобы дублей, путаницы не было

там еще по `модалке` правки будут небольшие - выключение по клику на бэкдроп - пропс для хука.

и с `компонентом изображения` какойто косячок был, с последнего коммита на мастере, я временно этот компонент к старому состоянию откатил, еще не занимался

2024-06-12 06:40 UTC, effektivnayarabota1 commented
> * [Users page #24](https://github.com/atls/team-management/issues/24)
>   Сделана анимация сайдбара и layout страницы.
>   Нужно сделать модалки команды и уведомлений.

на твоей странице вот этот компонент если что:
![image](https://github.com/atls/team-management/assets/70315473/8a35e5b3-508b-470e-83a6-4ddb4f6e85c1)
![image](https://github.com/atls/team-management/assets/70315473/55f041ab-08e3-4b9f-86dd-8007e1a034c9)

2024-06-12 10:53 UTC, effektivnayarabota1 commented
> > * [Users page #24](https://github.com/atls/team-management/issues/24)
> >   Сделана анимация сайдбара и layout страницы.
> >   Нужно сделать модалки команды и уведомлений.
> 
> на твоей странице вот этот компонент если что: ![image](https://private-user-images.githubusercontent.com/70315473/338849997-8a35e5b3-508b-470e-83a6-4ddb4f6e85c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODk4MDgsIm5iZiI6MTcxODE4OTUwOCwicGF0aCI6Ii83MDMxNTQ3My8zMzg4NDk5OTctOGEzNWU1YjMtNTA4Yi00NzBlLTgzYTYtNGRkYjRmNmU4NWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEwNTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNDRkN2E5ZWJhODllMWFjNWQ1NzNiYTE4YTMxMzMwN2M2NzIxZmYwYmVkNzU1NmNiMmI3MjcwMjhmNTI4ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TfJmhn16tWnk1avY36ErsruHmcHMIRhnw2MAabJqvUg) ![image](https://private-user-images.githubusercontent.com/70315473/338849820-55f041ab-08e3-4b9f-86dd-8007e1a034c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODk4MDgsIm5iZiI6MTcxODE4OTUwOCwicGF0aCI6Ii83MDMxNTQ3My8zMzg4NDk4MjAtNTVmMDQxYWItMDhlMy00YjlmLTg2ZGQtODAwN2UxYTAzNGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEwNTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyM2M3MTU1ZjgzZTFiNjg2MGRhNzhiNTc2OGUzZTJhNWU3ZGI2MDNmNzZmODFhNDZmYjAyZWMzMjU0YmIyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m48o_Af73xFvW6sgQ7Y3AODi7QOt6q4vwRempAAQCEM)

а, он на обеих страницах используется. я добавлю в `title` фрагмент эту модалку

2024-06-17 03:03 UTC, ssagg commented
@Nelfimov привет. есть одна проблема с Тайпчек на главной странице. Сделал редирект с главной на наш дашбоард. но тайпчек упорно не видит этот модуль некста. добавил свойсвто appDir:true в next.config. но не помогло. Возможно бага. поставил ts-ignore.
  Error: Cannot find module 'next/navigation' or its corresponding type declarations.
➤ YN0000: │ 
➤ YN0000: │   1 | 'use client'
➤ YN0000: │   2 |
➤ YN0000: │ > 3 | import { useRouter } from 'next/navigation'
➤ YN0000: │     |                          ^
➤ YN0000: │   4 |
➤ YN0000: │   5 | const Page = () => {
➤ YN0000: │   6 |   const router = useRouter()
➤ YN0000: │           router.push('/dashboard/users')

2024-06-17 05:34 UTC, Nelfimov commented
Это только в `ts-ignore`

2024-06-17 05:39 UTC, Nelfimov requested changes

2024-06-17 05:39 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/dashboard/users/page.ts
> +'use client'
высоко по дереву

2024-06-17 05:39 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/dashboard/layout.tsx
> +'use client'
высоко

2024-06-17 05:39 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/registration/page.ts
> +'use client'
высоко

2024-06-17 05:39 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/page.tsx
>  'use client'
высоко

2024-06-17 05:39 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/page.tsx
> +import { useRouter } from 'next/navigation'
все ниже - в отдельный пакет в `pages`

2024-06-17 05:39 UTC, Nelfimov commented on app/entrypoints/renderer/package.json
> +    "@app/base-layout-fragment": "workspace:*",
эта зависимость сломает деплой

2024-06-17 05:39 UTC, Nelfimov commented on app/pages/users-page/src/users.constants.ts
> +export const USERS_DATA = [
на будущее - пользуйся `faker`

2024-06-17 05:39 UTC, Nelfimov commented on app/fragments/app-base-layout/src/base-layout.constants.ts
> +export const name = 'Bill Gates'
SCREAMING_SNAKE_CASE

2024-06-17 11:06 UTC, effektivnayarabota1 commented on app/entrypoints/renderer/src/app/page.tsx
> +import { useRouter } from 'next/navigation'
https://github.com/atls/team-management/tree/feat/organizations-page/app/pages/dashboard-redirect-page

2024-06-18 06:50 UTC, Nelfimov requested changes

2024-06-18 06:50 UTC, Nelfimov commented on app/pages/index-page/src/index.page.tsx
> +'use client'
опусти еще ниже, а тут пользуйся серверными методами

2024-06-18 06:50 UTC, Nelfimov commented on app/pages/registration-page/src/registration.page.tsx
> +'use client'
опустить ниже

2024-06-18 06:50 UTC, Nelfimov commented on app/pages/users-page/src/users.page.tsx
> +'use client'
опустить ниже. По необходимости - рефактор фрагментов

2024-06-19 07:33 UTC, Nelfimov submitted a review, later dismissed

2024-06-19 07:34 UTC, Nelfimov commented
конфликты

2024-06-19 19:40 UTC, ssagg commented
Единообразно переименовал все фрагменты, навел побольше порядка. Удалил некоторые лишние стили Кирилла (с ним обсудили). Добавил прелоадер. Поправил ссылки в сайдбаре.

2024-06-20 06:35 UTC, Nelfimov approved these changes
поправь одно замечание и мержим

2024-06-20 06:35 UTC, Nelfimov commented on app/entrypoints/renderer/src/next.config.js
> +  images: {
два `next.config.js` вышло

2024-06-20 11:21 UTC, ssagg commented
@Nelfimov поправил. сделай мерж подалуйста

2024-06-20 11:23 UTC, Nelfimov approved these changes

2024-06-20 11:24 UTC, merged