Feat/get organizations data
atls/team-management pull request #38
Opened 2024-07-03 18:07 UTC by effektivnayarabota1

2024-07-12 17:08 UTC, effektivnayarabota1 commented
- остановился на том, что `диспетчер` не подключается через `useContext` в левой кнопке в карточке организации
  - в правой подключается. вложенность у них одинаковая, ничем модалки не отличаются.

2024-07-22 06:16 UTC, Nelfimov requested changes
1. Визуальные баги в сафари:

![Screenshot 2024-07-22 at 08 54 44](https://github.com/user-attachments/assets/44d3a49f-3598-4875-a139-90606498bb76)

2. Ошибка запроса на странице организаций:

![Screenshot 2024-07-22 at 08 54 50](https://github.com/user-attachments/assets/0ecc6a28-9fa6-479d-b2f7-790dbe0db126)

3. Как мне видится нужно сделать перезапрос прав приложения. Вот моя ситуация - я не дал приложению доступ к некоторым организациям (либо организации появились после авторизации в приложении) - приложение должно запросить заново разрешения на всех орги.

2024-07-22 06:16 UTC, Nelfimov commented on ui/input/src/github-search-users-input/github-search-users-input.component.tsx
> +export const GithubSearchUsersInput = forwardRef<HTMLInputElement, SelectInputProps>(
нейминг файла и компонента - зачем привязываться к контексту гитхаба, если тут просто поисковый инпут?

2024-07-22 06:16 UTC, Nelfimov commented on ui/input/src/github-search-users-input/input-change.hook.ts
> +export const inputChangeHook = ({
интерфейс

2024-07-22 06:16 UTC, Nelfimov commented on ui/input/src/github-search-users-input/get-searched-users.hook.ts
> +export const getSearchedUsers = async ({ searchQuery, suggestedItemsDispatch, toast }) => {
Так же - этому хуку не место в ui - тут конкретная бизнес логика. Об этом говорит зависимость от `@globals/data`. Очень похоже, что это уже фрагмент.

2024-07-22 06:16 UTC, Nelfimov commented on ui/toast-notification/src/index.ts
> +export * from './use-toast.hook.js'
плоская структура файлов, нет разделения на слои. Тут и ui, и контекст, и редьюсер...

1. Раскидай все по слоям
2. Контекст отдельно в `store`

2024-07-22 06:16 UTC, Nelfimov commented on ui/toast-notification/src/toast-notification.constants.ts
> +export const HIDE_DELAY_5SEC = 1000 * 5
нейминг - хорошо что указал единицу измерения, но число здесь лишнее. Поменяешь значение константы - придется по всем проекту менять ссылку на конснтанту

2024-07-22 06:16 UTC, Nelfimov commented on globals/data/src/octokit-rest-client/index.ts
> +export * from './remove-organization-member.js'
назвал папку `octokit-rest-client`, т.е. существительное-объект, а экспортируешь функции

2024-07-22 06:16 UTC, Nelfimov commented on globals/interfaces/src/interfaces.ts
> +// TODO нужны ли нам эти типы, если data приходит с query,
если это есть в генерируемых файлах - то нет. Можешь просто экспортировать интерфейсы из генерируемых файлов

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-add-member-modal/src/add-member-modal.component.tsx
> +        <Text fontSize='normal.increased'>{formatMessage({ id: 'add-member-modal.header' })}</Text>
Можно так а можно `<FormattedMessage ... />`. Будет читаемее

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-add-member-to-organization-modal/src/add-member-to-organization-modal.component.tsx
> +  useEffect(
смешал функционал и рендер. Вынеси логику в хук

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-add-member-to-organization-modal/src/get-organization-teams.hook.ts
> +export const getOrganizatoinTeamsHook = async ({ organizationId, setTeamsData, toast }) => {
интерфейс

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-add-member-to-organization-modal/src/get-organization-teams.hook.ts
> +const ORGANIZATION_TEAMS_LIMIT = 16
коснтанты в отдельном файле

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-add-member-to-organization-modal/src/invite-button-click.hook.ts
> +export const inviteButtonClickHook = async ({
интерфейс

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-add-member-to-organization-modal/src/invite-button-click.hook.ts
> +        // Можно ли выводить ошибку промиса в основной поток?
да. Только у тебя асинхронная функция, будет правильнее использовать https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-add-member-to-organization-modal/src/set-button-active.hook.ts
> +export const setButtonActiveHook = ({ inviteButtonState, selectedUsers, setInviteButtonState }) => {
интерфейс

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-organization-card-grid/src/get-organizations-data.hook.ts
> +export const getOrganizationsData = async ({ setOrganizationsData, toast }) => {
в хуки

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-registration/src/registration.constants.ts
> +// export const GH_AUTH_SCOPES = 'user:email read:org'
коммент?

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-users-modal/src/get-organization-members.hook.ts
> +export const getOrganizationMembersHook = async ({ organizationId, setMembersData, toast }) => {
в хуки

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-users-modal/src/get-organization-members.hook.ts
> +const MEMBERS_LIMIT = 32
в коснтанты

2024-07-22 06:16 UTC, Nelfimov commented on app/fragments/app-users-modal/src/remove-member.hook.ts
> +export const removeMemberHook = ({
1. в хуки
2. интерфейс

2024-07-22 09:49 UTC, effektivnayarabota1 commented
> 3\. Как мне видится нужно сделать перезапрос прав приложения. Вот моя ситуация - я не дал приложению доступ к некоторым организациям (либо организации появились после авторизации в приложении) - приложение должно запросить заново разрешения на всех орги.

@Nelfimov можно при нажатии, например, на `шестеренку` перебрасывать юсера на настройку приложения в самом `гитхабе` [по этой ссылке](https://github.com/settings/connections/applications/Ov23li9kGqtVre5AFIeA). 
функций больше - можно отозвать доступ от организации, добавить новую, полностью перекрыть доступ

можно как ты пишешь - удалить авторизацию и запросить новую, но так, мне кажется, `UX` пострадает

2024-07-22 09:51 UTC, Nelfimov commented
> можно как ты пишешь - удалить авторизацию и запросить новую, но так, мне кажется, `UX` пострадает

согласен. Засинкайся с дизайном и идем дальше

2024-07-22 14:36 UTC, effektivnayarabota1 commented on ui/toast-notification/src/index.ts
> +export * from './use-toast.hook.js'
про `стор` не понимаю
нужно вот этот функционал вынести?

```ts
export const useToast = () => {
  const toastNotificationDispatch = useContext(ToastNotificationDispatchContext) as DispatchFuncType

  return {
    notify: (text: string) =>
      toastNotificationDispatch({
        type: 'notify',
        toastNotification: { type: 'base', text, code: 0 },
      }),
    error: (text: string, code = 0) =>
      toastNotificationDispatch({
        type: 'notify',
        toastNotification: { type: 'error', text, code },
      }),
  }
}

```

2024-07-22 15:02 UTC, Nelfimov commented on ui/toast-notification/src/index.ts
> +export * from './use-toast.hook.js'
В UI должны быть примитивные компоненты, основная задача которых - рендерить что им передали и выполнять то, что сказали. А у тебя сейчас выходит конкретная реализация с контекстом. Поэтому я и предлагаю тебе контекст и все с ним связанное вытащить в `store` слой.

2024-07-23 12:00 UTC, effektivnayarabota1 commented on app/fragments/app-add-member-to-organization-modal/src/add-member-to-organization-modal.component.tsx
> +  useEffect(
не понимаю как вынести логику, если тут 2 `эффека` и два `хендлера`. все на **разных** переменных
вынести верстку?

2024-07-23 12:26 UTC, Nelfimov commented on app/fragments/app-add-member-to-organization-modal/src/add-member-to-organization-modal.component.tsx
> +  useEffect(
Эффекты можешь вызывать в хуках. Хэндлеры могут быть экспортируемой из хука функцией  изменения состояния

2024-07-24 05:07 UTC, Nelfimov commented on ui/toast-notification/src/toast-notification.constants.ts
> +export const HIDE_DELAY_5SEC = 1000 * 5
не исправлено

2024-07-24 05:12 UTC, Nelfimov reviewed
`stores` подними в корень

2024-07-24 05:12 UTC, Nelfimov commented on globals/data/src/octokit-rest-client/octokit-rest-client.ts
> +export const octokitRestClient = (token: string) => {
тогда уже `createOctokitRestClient` раз это функция

2024-07-24 05:21 UTC, Nelfimov requested changes
![Screenshot 2024-07-24 at 08 19 25](https://github.com/user-attachments/assets/f73558ac-846c-4d38-be46-b4b4703b1e10)
![Screenshot 2024-07-24 at 08 20 04](https://github.com/user-attachments/assets/61f078a4-7123-4ca2-8e6b-b97f781aa1cc)

Так же - вынеси `store` в корень проекта. Ну и `stores` нейминг

2024-07-24 06:20 UTC, effektivnayarabota1 commented
> Кнопка в disabled даже после ввода email

этой формой не занимался, думаю, она к странице `users` относится.
делал только страницу `organizations`

2024-07-24 06:40 UTC, effektivnayarabota1 commented
> Ошибка на странице организаций

вот этот момент не понимаю. ты не менял права приложения? внизу сайдбара разместили кнопку с шестеренкой

2024-07-24 06:43 UTC, Nelfimov commented
> > Ошибка на странице организаций
> 
> вот этот момент не понимаю. ты не менял права приложения? внизу сайдбара разместили кнопку с шестеренкой

![image](https://github.com/user-attachments/assets/e3bf21cf-1327-4b8e-a7b7-c28a4de79d96)

2024-07-24 07:24 UTC, effektivnayarabota1 commented
@Nelfimov правки внес, ревью запросил

в `сафари` както отличается работа с `куки`? сейчас у меня есть хелпер, который `строку` (куки) собирает в `объект` (куки).

добавил проверку токена при запросе организаций, должен вернуть ошибку если он будет `false`

`webKit` у себя проверил, все работает корректоно. перезаходил через оба браузера - без изменений.

2024-07-24 07:26 UTC, effektivnayarabota1 commented
> `webKit` у себя проверил

![image](https://github.com/user-attachments/assets/596a4da9-2190-4bac-bd48-17ade44139fb)

2024-07-24 08:09 UTC, Nelfimov approved these changes

2024-07-24 08:09 UTC, merged

2024-07-24 08:19 UTC, effektivnayarabota1 commented
@Nelfimov организации отрисовались?

2024-07-24 08:48 UTC, Nelfimov commented
@effektivnayarabota1 да. Нужно было перелогиниться. Тут два варианта:
- либо обновленные разрешения для приложения схватываются только после перелогина
- либо у меня старые креды остались