Feat/users page
atls/team-management pull request #42
Opened 2024-07-26 09:55 UTC by effektivnayarabota1

2024-07-31 16:46 UTC, effektivnayarabota1 commented
@Nelfimov 
- сделал те проверки, что могу без сторонних сервисов, только `гитхаб` - `2fa` и `основная организация`
- прочертил маршруты для пропсов
- добавил хук удаления из организации в карточке юсера
- перечертил пару компонентов, пару фрагментов
- выправил интерфейсы

---

1. основное мясо вот в этом хуке: https://github.com/atls/team-management/blob/feat/users-page/app/fragments/app-member-cards-grid/src/hooks/get-members-data.hook.ts
2. большая константа онбординга вот тут: https://github.com/atls/team-management/blob/feat/users-page/app/fragments/app-member-cards-grid/src/member-cards-grid.constants.ts
   - возможно её нужно вынести?
   
- с объектами получилось запутанно у меня, но работает.
- я хотел избежать дополнительных запросов, потомучто запрашвать данные организации для каждого пользователя может быть дорого в плане лимитов.
- поэтому делаю через один запрос.
- мы запрашиваем организации, в них юсеры, но рендинить нам надо юсеров, а в них организации. [вот здесь это происходит](https://github.com/atls/team-management/blob/feat/users-page/app/fragments/app-member-cards-grid/src/hooks/get-members-data.hook.ts)
- делаю промежуточный объект со `связями юсер -> организации`, потом собираю `массив с мемберами` и связываю `мембера с организацией` из `первого объкта`. + фильтр на уникальность. + добавляю параметр условия онбординга `onbordingData`
-  для меня это остается немного запутанным моментом, поэтому расписал на всякий случай.

запрашиваю ревью

2024-08-01 05:56 UTC, Nelfimov requested changes
1. Встреченные ошибки:

![Screenshot 2024-08-01 at 08 37 28](https://github.com/user-attachments/assets/ff18b40a-bd11-47ad-b0f1-d12d70bf5735)
![Screenshot 2024-08-01 at 08 37 47](https://github.com/user-attachments/assets/1ffc643c-ae39-48ef-aaf3-501caea38a23)

2. Не смог оставить замечание - `get-onboarding-condition-icon.hook.ts` используй свитч

2024-08-01 05:56 UTC, Nelfimov commented on globals/mail/src/send-mail.mail.ts
>  export const sendMail = async (mailTemplate) => {
а где же интерфейс?

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-invite-member-modal/src/hooks/send-invite-email.hook.ts
> +export const sendInviteEmailHook: SendInviteEmailHookType = async ({ emails, selectedInvites }) => {
try catch

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-card/src/helpers/index.ts
> +export * from './get-progressbar-percents.helper.js'
все это - getters, а не `helpers`

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-card/src/member-card.constants.tsx
> +export const getOnbordingConditionList = ({ theme }: { theme: ThemeType }) => {
интерфейс возврата

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-card/src/image-group/image-group.component.tsx
> +export const ImageGrop: FC<ImageGroupProps> = ({
1. очепятка
2. из нейминга непонятно за что отвечает
3. 18 файлов - возможно стоит вынести отдельным фрагментом

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-cards-grid/src/hooks/get-members-data.hook.ts
> +    const response = (await client(GET_VIEWER_ALL_ORGANIZATIONS_ALL_MEMBERS, {
ты ведь можешь это с созданием клиента вынести в функцию в `globals`

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-cards-grid/src/hooks/get-members-data.hook.ts
> +export const getMembersData: GetMembersDataType = async ({
попробуй упростить:
1. раздели получение данных в `data`
2. преобразование можно оставить в `hooks`

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-cards-grid/src/hooks/get-members-withot-2fa.hook.ts
> +  const query = getGithubOrganizationMembersWithout2fa({
это и выше - можно в `globals`

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-cards-grid/src/member-cards-grid.component.tsx
> +  const timerMilliseconds = 17000
в коснтанты

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-cards-grid/src/member-cards-grid.component.tsx
> +  MemberCardsGridHook({
нейминг не по конвенции

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-cards-grid/src/member-cards-grid.constants.ts
> +    // done
лишние комменты убрать, оставшиеся в todo

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-member-cards-grid/src/member-cards-grid.hook.ts
> +  // organizationsData,
коммент

2024-08-01 05:56 UTC, Nelfimov commented on app/fragments/app-organizations-modal/src/organization-element/hooks/remove-member-from-organization.hook.ts
> +    await restClient(...query)
в `globals`

2024-08-01 06:02 UTC, effektivnayarabota1 commented on globals/mail/src/send-mail.mail.ts
>  export const sendMail = async (mailTemplate) => {
)

2024-08-01 06:12 UTC, effektivnayarabota1 commented on app/fragments/app-member-cards-grid/src/member-cards-grid.component.tsx
> +  MemberCardsGridHook({
вроде так хуки компонентов и называл всегда
использовать `useMemberCardsGrid`?

2024-08-01 06:13 UTC, Nelfimov commented on app/fragments/app-member-cards-grid/src/member-cards-grid.component.tsx
> +  MemberCardsGridHook({
уже лучше. Только пересмотри название когда поправишь функционал

2024-08-01 06:33 UTC, effektivnayarabota1 commented on app/fragments/app-member-cards-grid/src/hooks/get-members-data.hook.ts
> +export const getMembersData: GetMembersDataType = async ({
у меня в этой функции есть вложенные в `loop` `loop'ы`
я изначально писал через `continue`, на `чеке` `линтер` жаловался на `continue`, вложил в `if`
как лучше делать?

2024-08-01 06:40 UTC, effektivnayarabota1 commented on app/fragments/app-member-cards-grid/src/hooks/get-members-data.hook.ts
> +export const getMembersData: GetMembersDataType = async ({
в доках eslint нашел такую запись, насколько это правда:
`"When used incorrectly it makes code less testable, less readable and less maintainable. Structured control flow statements such as if should be used instead."`

2024-08-01 06:53 UTC, Nelfimov commented on app/fragments/app-member-cards-grid/src/hooks/get-members-data.hook.ts
> +export const getMembersData: GetMembersDataType = async ({
Дроби на мелкие части и выноси

2024-08-02 07:16 UTC, Nelfimov requested changes

2024-08-02 07:16 UTC, Nelfimov commented on globals/constants/src/init-onbording-data.constant.ts
> +    // TODO нет данных collaborators по предложенному ендпоинту
no russian

2024-08-02 07:16 UTC, Nelfimov commented on globals/third-party/package.json
> +  "name": "@globals/third-party",
что такое `third-party`? Так то тут все библиотеки third-party. Если тут речь по GH, то у тебя и в `data` - GH

2024-08-02 07:16 UTC, Nelfimov commented on app/fragments/app-member-card/src/member-card.constants.tsx
> +  theme: ThemeType
дублирование - у тебя выше обозначен интерфейс

2024-08-05 11:36 UTC, Nelfimov approved these changes

2024-08-05 11:36 UTC, merged