feat: entrypoint
atls/team-management pull request #6
Opened 2024-05-06 15:11 UTC by bbulakh

Closes https://github.com/atls/team-management/issues/2

2024-05-06 15:32 UTC, Nelfimov requested changes
обрати внимание - чеки не прошли. Завалились на `install`

Ошибка связана с тем что не запускал `yarn` и не коммитил изменения

2024-05-07 10:42 UTC, Nelfimov approved these changes

2024-05-07 10:47 UTC, Nelfimov submitted a review, later dismissed

2024-05-07 10:56 UTC, Nelfimov commented
@bbulakh товарищ, у вас тут конфликты нарисовались.

2024-05-07 11:33 UTC, bbulakh commented
@Nelfimov всё сломалось, можем по-быстрому в д?

2024-05-07 11:45 UTC, Nelfimov commented
да. Можешь такое писать в телегу, тут излишне

2024-05-07 12:27 UTC, merged