Feat/figma theme
atls/team-management pull request #7
Opened 2024-05-06 16:34 UTC by effektivnayarabota1

### Вопросы.
+ огромное количество теней, в файле с тенями, это нормально? в макете только один стиль.
+ не все текстовые стили нашел. в фигме вижу 39й размер, в файлах такого нет.
+ в фигме вижу только шрифт - *Inter*, в файлах его нет.

Как работает этот скрипт? Он проходится именно по *стилям в макете* или бегает по всему макету?
Я сравнивал итоговые данные именно со стилями.
**P.S. Под стилями имеюю ввиду данные с панели справа.**

2024-05-06 16:41 UTC, Nelfimov requested changes
Все верно получил.

Теперь сделай провайдер темы. Можешь подсмотреть в `hyperion` либо в других наших проектах.

2024-05-06 16:42 UTC, Nelfimov commented
> * огромное количество теней, в файле с тенями, это нормально? в макете только один стиль.
Вероятно нет. Можешь лишние убрать - по ходу работы над проектом нужные добавим.

> * не все текстовые стили нашел. в фигме вижу 39й размер, в файлах такого нет.
Можешь вручную добавить сейчас либо по ходу разработки.

> * в фигме вижу только шрифт - _Inter_, в файлах его нет.

Можно вручную добавить.

> Как работает этот скрипт? Он проходится именно по _стилям в макете_ или бегает по всему макету? Я сравнивал итоговые данные именно со стилями. **P.S. Под стилями имеюю ввиду данные с панели справа.**

99% что бегает по всему макету. Это область для доработки.

2024-05-06 17:37 UTC, effektivnayarabota1 commented
запушил коммит и забыл отформатировать `yarn check`
на локальном репозитории поправил и сделал `git --amend`

коммиты слить не получилось, как делать лучше в таких случаях?

2024-05-06 17:49 UTC, Nelfimov commented
squash и force push. До ревью форс пуш - можно.

2024-05-07 10:51 UTC, Nelfimov approved these changes

2024-05-07 10:52 UTC, merged