Feat/UI parts
atls/team-management pull request #9
Opened 2024-05-07 12:45 UTC by ssagg

Почему Card может быть недоступен? модуль не виден как-будто. сделал ui/card отдельным пакетом, в зависимостях он есть. Может его собрать еще надо?
![Screenshot from 2024-05-07 09-20-06](https://github.com/atls/team-management/assets/104500533/432421ef-f38e-46af-8d54-14ec5f67135d)
![Screenshot from 2024-05-07 09-19-45](https://github.com/atls/team-management/assets/104500533/0d900fec-964b-4f60-baef-82e4c04bc085)
![Screenshot from 2024-05-07 09-19-24](https://github.com/atls/team-management/assets/104500533/26e77aa3-fdd1-4da4-94b5-9965588aa048)

2024-05-07 12:53 UTC, Nelfimov commented
Ошибся с раширением тут:

https://github.com/atls/team-management/blob/719da5d59ad7b3d5094cf65d2f5f6694b6a4aa1a/ui/card/package.json#L5

Возьми из мастера энтрипоинт.

2024-05-10 02:20 UTC, ssagg commented
Привет. Помоги пожалуйста с сайдбаром.
Почему-то он не видит пакет @atls-ui-parts/switch'. Уже и в разные заисимости его добавлял. Никак.
Module not found: Can't resolve '@atls-ui-parts/switch'

И подскажи по Button. Кнопки должны как-то генерироваться или надо делать по анлогии с Автаром? Писать свой копонент, но тянуть зависимости из hyperion?

2024-05-10 06:39 UTC, Nelfimov requested changes
Как минимум твой сайдбар - не отдельный пакет. Пакет характеризуется своим package.json и зависимостями. 

Отсюда ошибка.

2024-05-10 06:39 UTC, Nelfimov commented on app/entrypoints/renderer/package.json
> +  "peerDependencies": {
Это энтрипоинт - родительский пакет. Соответственно он не сможет ни от кого получить эту зависимость.

2024-05-10 06:47 UTC, Nelfimov commented
> И подскажи по Button. Кнопки должны как-то генерироваться или надо делать по анлогии с Автаром? Писать свой копонент, но тянуть зависимости из hyperion?

Посмотри как сделано в drumin - там button собирается из зависимостей, в том числе @atls-ui-parts/button, а с помощью генератора получает необходимые «варианты» отрисовки.

2024-05-10 20:07 UTC, ssagg commented
> Как минимум твой сайдбар - не отдельный пакет. Пакет характеризуется своим package.json и зависимостями.
> 
> Отсюда ошибка.

Половина файлов не закомитилось( все в пакете. Пакеты в пакетах. Посмотри еще раз пожалуйста.

2024-05-11 15:04 UTC, Nelfimov requested changes
Добавил фикс.

Проверь мой коммит, особенно `yarnrc.yaml`. 

Вкратце - `yarn pnp` не всегда корректно отрабатывает зависимости у детей. Поэтому их необходимо модифицировать.

Подробности тут: https://yarnpkg.com/configuration/yarnrc#packageExtensions

2024-05-14 01:49 UTC, ssagg commented
@Nelfimov 
добавил все компоненты на страницу. начал заниматься стилизацией кнопок через theme с последующей генерацией стилей. Дальше компоненты надо кастомизировать более глубоко и описывать стили.

2024-05-14 05:31 UTC, Nelfimov requested changes
резюме замечаний:
- https://github.com/atls/hyperion/wiki/Что-такое-peerDependencies
- компоненты должны отдавать минимально необходимый набор пропсов, с которыми мы будем взаимодействовать в проекте. Лучше поначалу меньше, а затем "наращивать"

2024-05-14 05:31 UTC, Nelfimov commented on package.json
> +  "dependencies": {
это здесь лишнее - в рутовом package.json мы обозначаем инструменты которые нужны проекту для работы с кодом, но не зависимости конкретных сервисов

2024-05-14 05:31 UTC, Nelfimov commented on package.json
> +    "@types/styled-system": "5.1.22",
аналогично

2024-05-14 05:31 UTC, Nelfimov commented on app/entrypoints/renderer/package.json
> +    "@ui/avatar": "workspace:*",
локальные зависимости `workspace:*` надо в `devDependencies` - это баг нашего инструментария.

2024-05-14 05:31 UTC, Nelfimov commented on app/entrypoints/renderer/package.json
>      "start": "node dist/src/index.cjs"
у билд скрипта надо так же копировать папку `public`, тем более ты туда уже добавил некую статику. Иначе в деве у тебя все будет хорошо, а при билде - статики не будет

2024-05-14 05:31 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/page.tsx
> +        valueWidth={'3547px'}
обычно кнопка настраивается только через `size` и `variant`. Остальное можно доделать через `Layout`

2024-05-14 05:31 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/page.tsx
> +        size={'middlingRoundedPaddingtStyles'}
здесь и ниже - `{}` лишние у пропсов

2024-05-14 05:31 UTC, Nelfimov commented on ui/avatar/src/avatar.component.tsx
> +  const StoryAvatar = styled.div(
видно что взял из историй. Важно - каждому компоненту отдельный файл.

2024-05-14 05:31 UTC, Nelfimov commented on ui/avatar/src/avatar.interfaces.ts
> +  icon?: any
`any` нельзя

2024-05-14 05:31 UTC, Nelfimov commented on ui/avatar/src/index.ts
> +export * from '@atls-ui-parts/avatar'
нужно ли тебе экспортировать это если ты создал свой аватар и используешь его по проекту?

2024-05-14 05:31 UTC, Nelfimov commented on ui/avatar/package.json
> +    "@emotion/react": "11.11.3",
посмотри https://github.com/atls/hyperion/wiki/Что-такое-peerDependencies

сейчас у тебя сделано так что каждый пакет будет инициализировать свой реакт и прочие зависимости

2024-05-14 05:31 UTC, Nelfimov commented on ui/avatar/package.json
> +    "string-to-color": "2.2.2",
нужно ли это?

2024-05-14 05:31 UTC, Nelfimov commented on ui/text/package.json
> +  "dependencies": {
https://github.com/atls/hyperion/wiki/Что-такое-peerDependencies

2024-05-14 05:31 UTC, Nelfimov commented on ui/sidebar/package.json
> +  "dependencies": {
https://github.com/atls/hyperion/wiki/Что-такое-peerDependencies

2024-05-14 05:31 UTC, Nelfimov commented on ui/layout/package.json
> +  "dependencies": {
https://github.com/atls/hyperion/wiki/Что-такое-peerDependencies

2024-05-14 05:31 UTC, Nelfimov commented on ui/image/package.json
> +  "dependencies": {
https://github.com/atls/hyperion/wiki/Что-такое-peerDependencies

2024-05-14 05:31 UTC, Nelfimov commented on ui/card/src/card.components.tsx
> +// import profile        from '../assets/profile.png'
и тут и в паблике. Лучше оставить в паблике

2024-05-14 05:31 UTC, Nelfimov commented on ui/card/src/card.components.tsx
> +// import { NextImage }  from '@ui/image'
закоментированный код - нельзя

2024-05-14 05:31 UTC, Nelfimov commented on ui/card/src/card.components.tsx
> +export const Card = ({ children }) => {
интерфейс

2024-05-14 05:31 UTC, Nelfimov commented on ui/card/src/card.components.tsx
> +        <ImageBlock src='https://www.figma.com/file/2vNHefkDcMKAFSnw69RbMM/image/efb6f62056dfdd8faea9ed52a81fbdcd844baa28' />
фигма может измениться. Используй то что добавил в паблик

2024-05-16 14:31 UTC, ssagg commented on ui/button/src/button.generator.ts
> +import { AppearanceStyleGenerator } from '@atls-ui-generators/button'
без него не работате генератор

2024-05-16 15:43 UTC, Nelfimov commented on ui/avatar/src/avatar.interfaces.ts
> +  contentType: string
в компоненте ты уже указал какие ожидаешь строки - перечисли тут через юнион

2024-05-16 15:45 UTC, Nelfimov commented on ui/theme/src/theme/backgrounds.ts
> +  mainBackground: '#F8F8F8',
`background` не обязателен - все уже в нужном объекте

2024-05-16 15:46 UTC, Nelfimov commented on ui/tag/src/tag.interfaces.ts
> +  fontSize?: object
конкретизируй `object` через `Record`

2024-05-16 15:47 UTC, Nelfimov commented on ui/image/package.json
> +  "dependencies": {
по прежнему актуально

2024-05-16 15:47 UTC, Nelfimov commented on ui/card/src/card.components.tsx
> +      boxShadow='0px 4px 20px 0px #00000040'
из темы

2024-05-16 15:48 UTC, Nelfimov commented on ui/card/src/card.components.tsx
> +      borderRadius={24}
все числа можно так же в тему

2024-05-17 02:46 UTC, ssagg commented on ui/avatar/src/avatar.component.tsx
> +  const Container = styled.div(
@Nelfimov помоги с этим компонентом, не пойму, как пропсы прокинуть. Посомтрел в других проектах, и там  везде контейнер находится внутри основного компонента и не выделяется в отдельный. Последние попытки в свежем PR.

2024-05-17 02:47 UTC, ssagg commented
@Nelfimov помоги с Avatar компонентом, не пойму, как пропсы прокинуть. Посомтрел в других проектах, и там везде контейнер находится внутри основного компонента и не выделяется в отдельный. Последние попытки в свежем PR.

2024-05-17 07:08 UTC, Nelfimov requested changes
запушил пример. Можешь продолжить в таком же духе.

Поставь себя ответственным за этот пр.

Закрой ненунжный пр.

2024-05-20 06:19 UTC, Nelfimov requested changes
1. `PropsWithChildren`
2. замечания резолвит ревьюер
3. обновить версии `@atls...` по проекту `yarn upgrade-interactive`
4. перезапустить генераторы (иконки, баттоны)
5. пересмотри какие пропсы ты открываешь у компонентов - они должны быть на "минималках"

2024-05-20 06:19 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/page.tsx
> +    <Layout></Layout>
здесь не нужно - в page добавим конкретную страницу

2024-05-20 06:19 UTC, Nelfimov commented on app/entrypoints/renderer/src/app/page.tsx
> +  <ThemeProvider>
перенести в layout.tsx

2024-05-20 06:19 UTC, Nelfimov commented on app/entrypoints/renderer/package.json
> +    "@ui/avatar": "workspace:*",
зависимости ниже не нужны уже

2024-05-20 06:19 UTC, Nelfimov commented on ui/avatar/src/container/container.component.tsx
> +export const ContainerWrapper: FC<ContainerProps> = ({
`PropsWithChildren`

2024-05-20 06:19 UTC, Nelfimov commented on ui/avatar/src/container/container.interfaces.ts
> +  children?: React.ReactNode
не нужно с `PropsWithChildren`

2024-05-20 06:19 UTC, Nelfimov commented on ui/avatar/src/notification/notification.styles.ts
> +  top: '0',
все что ниже - возьми все из темы. Можно либо через хук либо через объект темы

2024-05-20 06:19 UTC, Nelfimov commented on ui/theme/src/theme/space.ts
> +export { space }
держи пустую строку для читаемости

2024-05-20 06:19 UTC, Nelfimov commented on ui/tag/src/tag.component.tsx
> +const Tag: FC<TagProps> = ({
1. нужны ли тебе все пропсы здесь или можно какие то "зашить" и оставить то, что действительно варьируется?
2. `PropsWithChildren`

2024-05-20 06:19 UTC, Nelfimov commented on ui/tag/src/tag.interfaces.ts
> +export interface TagProps {
пустая строка

2024-05-20 06:19 UTC, Nelfimov commented on ui/icons/package.json
> +    "@atls-ui-generators/icons": "0.0.2",
какая древняя версия

2024-05-20 06:19 UTC, Nelfimov commented on ui/condition/package.json
> +  "main": "src/index.ts",
компонент же готов в гиперионе. Тебе надо просто установить его и реэкспортировать. По аналогии с лэйаутом

2024-05-20 06:19 UTC, Nelfimov commented on ui/card/src/card.components.tsx
> +export const Card: FC<CardProps> = ({ children, theme }) => {
`PropsWithChildren`

2024-05-20 06:19 UTC, Nelfimov commented on ui/card/src/card.components.tsx
> +        <ImageBlock src='/profile.png' style={{ borderRadius: theme.radii.tl24tr24 }} />
`src` следует получать из пропсов - не у всех же будет одна и та же аватарка

2024-05-20 06:19 UTC, Nelfimov commented on ui/card/src/card.components.tsx
> +      boxShadow={theme.shadows.card}
если ты хочешь действительно через пропсы модифицировать компонент, то добавляй их в пропсы. В текущей реализации везде где ты захочешь использовать этот компонент придется тянуть дополнительно весь объект темы.

2024-05-20 06:19 UTC, Nelfimov commented on ui/button/tsconfig.generate.json
> +{
нужен ли здесь этот файл?

2024-05-20 06:19 UTC, Nelfimov commented on ui/button/src/icon-attachment/icon-attachment.interface.ts
> +  valueRadius?: string | object
`object` --> `Record`

2024-05-21 02:51 UTC, ssagg commented
Решил передалть компонет карточки и оставить только обертку по сути. А наполнятся компонентами она уже будет во фрагменте. Т.к. карточки сильно разные по дизайну

2024-05-21 08:20 UTC, Nelfimov requested changes

2024-05-21 08:20 UTC, Nelfimov commented on ui/sidebar/src/hooks/index.ts
> +export * from './use-pinned-state'
нейминг у всех - `use-pinned-state.hook` и далее

2024-05-21 08:20 UTC, Nelfimov commented on ui/sidebar/src/hooks/interfaces.ts
> +export type UseHoverStateResult = [boolean, (nextValue?: boolean | any) => void]
нейминг файла - надо конкретизировать к чему относится интерфейс. Напр. `use-hover.interfaces.ts`

2024-05-21 08:20 UTC, Nelfimov commented on ui/sidebar/src/item/index.ts
> +export * from './item.element'
раздели по папкам - `label`, `icon`, `item element`. На верхнем уровне - `item.component`

2024-05-21 08:20 UTC, Nelfimov commented on ui/sidebar/src/items/index.ts
> +export * from './items.component'
`items-list.component` тогда уж

2024-05-21 08:20 UTC, Nelfimov commented on ui/sidebar/src/pinner/pinner.styles.ts
> +  top: '80%',
в тему

2024-05-21 08:20 UTC, Nelfimov commented on ui/avatar/package.json
> +    "@atls-ui-parts/condition": "0.1.1",
советую сделать локальный `@ui/condition`, который будет реэкспортировать `Condition` в проекте.

2024-05-22 05:29 UTC, Nelfimov requested changes
+ конфликты

+ себя в ответственные за ПР

2024-05-22 05:29 UTC, Nelfimov commented on ui/theme/src/theme/backgrounds.ts
> +  itemSelected: '#F5F9FF',
контекст

2024-05-22 05:29 UTC, Nelfimov commented on ui/theme/src/theme/backgrounds.ts
> +  notification: '#508EE9',
контекст

2024-05-22 05:29 UTC, Nelfimov commented on ui/theme/src/theme/backgrounds.ts
> +  tagBlack: '#282828',
контекст

2024-05-22 05:29 UTC, Nelfimov commented on ui/theme/src/theme/backgrounds.ts
> +  divider: '#D7D7D7',
контекст

2024-05-22 05:29 UTC, Nelfimov commented on ui/theme/src/theme/shadows.ts
> +  switch: '0px 2px 4px 0px #00000033',
выше - контексты

2024-05-22 05:29 UTC, Nelfimov commented on ui/avatar/src/styles/base/base.styles.ts
> +export const createBaseStyles: styleFn = () => () => ({
ты же можешь в аргументы `styleFn` добавить тему, как здесь https://github.com/atls/hyperion/blob/346f6a43978912f3be4b09031933ab2a572907b2/ui-proto/switch/src/switch.styles.ts#L60

2024-05-22 05:29 UTC, Nelfimov commented on ui/button/src/button.styles.ts
> +  paddingLeft: 12,
паддинги здесь и ниже - из темы

2024-05-22 05:29 UTC, Nelfimov commented on ui/sidebar/src/sidebar.component.tsx
> +              height={theme.space.full}
здесь и ниже - используй либо строчный `'theme.space.full'` либо `useTheme`

2024-05-22 05:29 UTC, Nelfimov commented on ui/tag/src/tag.component.tsx
> +      fontWeight={theme.fontWeights.medium}
строчный либо `useTheme`

2024-05-22 15:02 UTC, effektivnayarabota1 commented on ui/sidebar/src/sidebar.component.tsx
> +              height={theme.space.full}
а это вообще точно компонент? тут куча вложенных компонентов

2024-05-23 05:31 UTC, Nelfimov requested changes
+ конфликты

2024-05-23 05:31 UTC, Nelfimov commented on ui/button/src/button.styles.ts
> +  paddingRight: 24,
тема

2024-05-23 05:31 UTC, Nelfimov commented on ui/logo/src/logo.component.tsx
> +const Logo: FC = ({ ...props }) => <AtlantisIcon width={190} height={24} />
`magic numbers`

2024-05-23 05:31 UTC, Nelfimov commented on ui/sidebar/src/sidebar.component.tsx
> +              height={theme.space.full}
ты прав - по количеству файлов/кода это уже мало похоже на компонент. В будущем возможно вынесем во фрагменты

2024-05-23 10:44 UTC, Nelfimov requested changes

2024-05-23 10:44 UTC, Nelfimov commented on ui/theme/src/theme/radii.ts
> +  f8: 8,
дубликаты

2024-05-23 12:16 UTC, merged